services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: portofolio-app
    container_name: portofolio-app
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - portofolio-network

  db:
    image: mysql:8.0
    container_name: portofolio-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: portofolio_db
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - portofolio-network

networks:
  portofolio-network:
    driver: bridge

volumes:
  dbdata: